/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.main.java.com.mycompany.paint;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JColorChooser;

/**
 *
 * @author sergio.lima
 */
public class NewJFrame extends javax.swing.JFrame {

    Color corAtual1;
    Color corAtual2;
    
    enum TipoFigura {tpPonto,tpRetangulo, tpReta, tpCirculo, tpPoligono, tpSpray, tpBorracha, tpCilindro, tpPiramide};
    
    Ponto p = new Ponto();
    Retangulo r = new Retangulo();
    D1 reta = new D1();
    Circulo circ = new Circulo();
    Poligono pol = new Poligono();
    Spray sp = new Spray();
    Borracha bo = new Borracha();
    Cilindro cilin = new Cilindro();
    Piramide piram = new Piramide();
    private TipoFigura tipoFigura = TipoFigura.tpPonto;
    ArrayList<Integer> a = new ArrayList();
    ArrayList<Integer> b = new ArrayList();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setResizable(true);
        jpCor2.setBackground(jpPaint.getBackground());
        corAtual2 = jpPaint.getBackground();
        corAtual1 = jpCor1.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        jpPaint = new javax.swing.JPanel();
        BtnPonto = new javax.swing.JButton();
        cbArea = new java.awt.Checkbox();
        jpCor1 = new javax.swing.JPanel();
        jpCor2 = new javax.swing.JPanel();
        BtnRet = new javax.swing.JButton();
        BtnCor1 = new javax.swing.JButton();
        BtnCor2 = new javax.swing.JButton();
        btnReta = new javax.swing.JButton();
        cbComprimento = new java.awt.Checkbox();
        btnCirculo = new javax.swing.JButton();
        cbPerimetro = new java.awt.Checkbox();
        btnPoligono = new javax.swing.JButton();
        btnSpray = new javax.swing.JButton();
        btnBorracha = new javax.swing.JButton();
        cbVolume = new java.awt.Checkbox();
        BtnCilin = new javax.swing.JButton();
        BtnPiram = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(java.awt.Color.white);
        setSize(new java.awt.Dimension(300, 300));
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jpPaint.setBackground(new java.awt.Color(153, 255, 255));
        jpPaint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpPaintMouseDragged(evt);
            }
        });
        jpPaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpPaintMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpPaintMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jpPaintLayout = new javax.swing.GroupLayout(jpPaint);
        jpPaint.setLayout(jpPaintLayout);
        jpPaintLayout.setHorizontalGroup(
            jpPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpPaintLayout.setVerticalGroup(
            jpPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        BtnPonto.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        BtnPonto.setText(".");
        BtnPonto.setContentAreaFilled(false);
        BtnPonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPontoMouseClicked(evt);
            }
        });

        cbArea.setLabel("Área");

        jpCor1.setBackground(new java.awt.Color(0, 0, 0));
        jpCor1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jpCor1Layout = new javax.swing.GroupLayout(jpCor1);
        jpCor1.setLayout(jpCor1Layout);
        jpCor1Layout.setHorizontalGroup(
            jpCor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jpCor1Layout.setVerticalGroup(
            jpCor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jpCor2.setBackground(new java.awt.Color(255, 255, 255));
        jpCor2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jpCor2Layout = new javax.swing.GroupLayout(jpCor2);
        jpCor2.setLayout(jpCor2Layout);
        jpCor2Layout.setHorizontalGroup(
            jpCor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jpCor2Layout.setVerticalGroup(
            jpCor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        BtnRet.setText("Retangulo");
        BtnRet.setContentAreaFilled(false);
        BtnRet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRetMouseClicked(evt);
            }
        });

        BtnCor1.setText("Cor Externa");
        BtnCor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCor1MouseClicked(evt);
            }
        });
        BtnCor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCor1ActionPerformed(evt);
            }
        });

        BtnCor2.setText("Cor Interna");
        BtnCor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCor2MouseClicked(evt);
            }
        });

        btnReta.setText("Reta");
        btnReta.setContentAreaFilled(false);
        btnReta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetaMouseClicked(evt);
            }
        });
        btnReta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetaActionPerformed(evt);
            }
        });

        cbComprimento.setLabel("Comprimento");

        btnCirculo.setText("Circulo");
        btnCirculo.setContentAreaFilled(false);
        btnCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCirculoMouseClicked(evt);
            }
        });
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        cbPerimetro.setLabel("Perimetro");

        btnPoligono.setText("Poligono");
        btnPoligono.setContentAreaFilled(false);
        btnPoligono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPoligonoMouseClicked(evt);
            }
        });
        btnPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoligonoActionPerformed(evt);
            }
        });
        btnPoligono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPoligonoKeyPressed(evt);
            }
        });

        btnSpray.setText("Spray");
        btnSpray.setContentAreaFilled(false);
        btnSpray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSprayMouseClicked(evt);
            }
        });
        btnSpray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSprayActionPerformed(evt);
            }
        });
        btnSpray.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSprayKeyPressed(evt);
            }
        });

        btnBorracha.setBackground(new java.awt.Color(204, 204, 204));
        btnBorracha.setText("Borracha");
        btnBorracha.setContentAreaFilled(false);
        btnBorracha.setDefaultCapable(false);
        btnBorracha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrachaMouseClicked(evt);
            }
        });
        btnBorracha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrachaActionPerformed(evt);
            }
        });

        cbVolume.setLabel("Volume");

        BtnCilin.setBackground(new java.awt.Color(204, 204, 204));
        BtnCilin.setText("Cilindro");
        BtnCilin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCilinMouseClicked(evt);
            }
        });
        BtnCilin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCilinActionPerformed(evt);
            }
        });

        BtnPiram.setBackground(new java.awt.Color(204, 204, 204));
        BtnPiram.setText("Piramide");
        BtnPiram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPiramMouseClicked(evt);
            }
        });
        BtnPiram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPiramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(BtnCor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnPonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCirculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPoligono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSpray)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorracha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCilin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPiram)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnCor1)
                    .addComponent(jpCor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCor2)
                    .addComponent(jpCor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnPonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPiram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtnCilin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(btnBorracha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSpray, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPoligono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCirculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnCor1.getAccessibleContext().setAccessibleName("cor 1");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:     
             
        
        
        
        
            
    }//GEN-LAST:event_formAncestorMoved

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
                
        
    }//GEN-LAST:event_formMousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseReleased

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed

    }//GEN-LAST:event_panelMousePressed

    private void BtnPiramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPiramActionPerformed

    }//GEN-LAST:event_BtnPiramActionPerformed

    private void BtnPiramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPiramMouseClicked
        tipoFigura = TipoFigura.tpPiramide;
    }//GEN-LAST:event_BtnPiramMouseClicked

    private void BtnCilinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCilinActionPerformed

    }//GEN-LAST:event_BtnCilinActionPerformed

    private void BtnCilinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCilinMouseClicked
        tipoFigura = TipoFigura.tpCilindro;
    }//GEN-LAST:event_BtnCilinMouseClicked

    private void btnBorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrachaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrachaActionPerformed

    private void btnBorrachaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrachaMouseClicked
        tipoFigura = TipoFigura.tpBorracha;
    }//GEN-LAST:event_btnBorrachaMouseClicked

    private void btnSprayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSprayKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSprayKeyPressed

    private void btnSprayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSprayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSprayActionPerformed

    private void btnSprayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSprayMouseClicked
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpSpray;
    }//GEN-LAST:event_btnSprayMouseClicked

    private void btnPoligonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPoligonoKeyPressed
        if (evt.getKeyChar()=='a'){
            pol.desenhar(jpPaint.getGraphics());
        }
    }//GEN-LAST:event_btnPoligonoKeyPressed

    private void btnPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoligonoActionPerformed

    private void btnPoligonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPoligonoMouseClicked
        tipoFigura = TipoFigura.tpPoligono;
    }//GEN-LAST:event_btnPoligonoMouseClicked

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseClicked
        tipoFigura = TipoFigura.tpCirculo;
    }//GEN-LAST:event_btnCirculoMouseClicked

    private void btnRetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetaActionPerformed

    private void btnRetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetaMouseClicked
        tipoFigura = TipoFigura.tpReta;
    }//GEN-LAST:event_btnRetaMouseClicked

    private void BtnCor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCor2MouseClicked
        corAtual2 = JColorChooser.showDialog(null, "Escolha uma cor: ", Color.BLACK);
        jpCor2.setBackground(corAtual2);
    }//GEN-LAST:event_BtnCor2MouseClicked

    private void BtnCor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCor1ActionPerformed

    }//GEN-LAST:event_BtnCor1ActionPerformed

    private void BtnCor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCor1MouseClicked
        corAtual1 = JColorChooser.showDialog(null, "Escolha uma cor: ", Color.BLACK);
        jpCor1.setBackground(corAtual1);
    }//GEN-LAST:event_BtnCor1MouseClicked

    private void BtnRetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRetMouseClicked
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpRetangulo;
    }//GEN-LAST:event_BtnRetMouseClicked

    private void BtnPontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPontoMouseClicked
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpPonto;
    }//GEN-LAST:event_BtnPontoMouseClicked

    private void jpPaintMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPaintMouseReleased
        // TODO add your handling code here:
        if (tipoFigura == TipoFigura.tpRetangulo) {

            //r.corInterna = JColorChooser.showDialog(null, "Escolha uma cor: ", Color.BLACK);

            r.base = evt.getX() - r.x;
            r.largura = evt.getY()- r.y;
            r.cor = jpCor1.getBackground();
            r.corInterna = corAtual2;
            r.showArea = cbArea.getState();
            r.showPerimetro = cbPerimetro.getState();
            r.desenhar(jpPaint.getGraphics());
        }
        if(tipoFigura == TipoFigura.tpReta){
            reta.X1 = evt.getX();
            reta.Y1 = evt.getY();
            reta.cor = corAtual1;
            reta.showComprimento = cbComprimento.getState();
            reta.desenhar(jpPaint.getGraphics());
        }
        if(tipoFigura == TipoFigura.tpCirculo){
            circ.showArea = cbArea.getState();
            circ.showPerimetro = cbPerimetro.getState();
            circ.X2 = evt.getX();
            circ.Y2 = evt.getX();
            circ.cor = corAtual1;
            circ.corInterna = corAtual2;
            circ.raio = (evt.getX()-circ.x)/2;
            circ.desenhar(jpPaint.getGraphics());

        }
        if(tipoFigura == TipoFigura.tpCilindro){
            cilin.showArea = cbArea.getState();
            cilin.showVolume = cbVolume.getState();

            cilin.X2 = evt.getX();
            cilin.Y2 = evt.getY();

            cilin.cor = corAtual1;
            cilin.corInterna = corAtual2;

            cilin.raio = (evt.getX()-cilin.x)/2;

            cilin.desenhar(jpPaint.getGraphics());
        }
        if(tipoFigura == TipoFigura.tpPiramide){
            piram.showArea = cbArea.getState();
            piram.showVolume = cbVolume.getState();

            piram.X2 = evt.getX();
            piram.Y2 = evt.getY();

            piram.cor = corAtual1;
            piram.corInterna = corAtual2;

            piram.desenhar(jpPaint.getGraphics());
        }
        a.clear();
        b.clear();
    }//GEN-LAST:event_jpPaintMouseReleased

    private void jpPaintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPaintMousePressed
        // TODO add your handling code here:

        if (tipoFigura == TipoFigura.tpPonto){
            p.x = evt.getX();
            p.y = evt.getY();
            p.cor = jpCor1.getBackground();
            p.desenhar(jpPaint.getGraphics());
        }
        if (tipoFigura == TipoFigura.tpRetangulo) {
            r.x = evt.getX();
            r.y = evt.getY();

        }
        if (tipoFigura == TipoFigura.tpReta){
            reta.x = evt.getX();
            reta.y = evt.getY();
        }
        if (tipoFigura == TipoFigura.tpCirculo){
            circ.x = evt.getX();
            circ.y = evt.getY();
        }
        if (tipoFigura == TipoFigura.tpPoligono){
            pol.cor = corAtual1;
            pol.corInterna = corAtual2;
            pol.adicionarPontos(evt.getX(), evt.getY());
            
            if( pol.listaPontos.size() >= 3 && evt.getButton() == MouseEvent.BUTTON2){
                pol.desenhar(jpPaint.getGraphics());
            }
        }
        if(tipoFigura == TipoFigura.tpCilindro){
            cilin.x = evt.getX();
            cilin.y = evt.getY();
        }
        if(tipoFigura == TipoFigura.tpPiramide){
            piram.x = evt.getX();
            piram.y = evt.getY();
        }
        /*if (tipoFigura == TipoFigura.tpSpray){
            sp.G = jpPaint.getGraphics();
            sp.cor = corAtual1;
            sp.min_valX = evt.getX()-50;
            sp.max_valX = evt.getX()+50;
            sp.min_valY = evt.getY()-50;
            sp.max_valY = evt.getY()+50;
            sp.desenhar();

        }*/
    }//GEN-LAST:event_jpPaintMousePressed

    private void jpPaintMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPaintMouseDragged
        if(tipoFigura == TipoFigura.tpBorracha){
            bo.x = evt.getX();
            bo.y = evt.getY();
            bo.cor = jpPaint.getBackground();
            bo.desenhar(jpPaint.getGraphics());
        }
        if(tipoFigura == TipoFigura.tpSpray){
            a.add(evt.getX());
            //b.add(evt.getY());
            sp.cor = corAtual1;

            for(int i =0 ; i< a.size()-1; i++){
                sp.G = jpPaint.getGraphics();
                sp.min_valX = evt.getX()-50;
                sp.max_valX = evt.getX()+50;
                sp.min_valY = evt.getY()-50;
                sp.max_valY = evt.getY()+50;
                sp.desenhar();
            }
        }
    }//GEN-LAST:event_jpPaintMouseDragged
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCilin;
    private javax.swing.JButton BtnCor1;
    private javax.swing.JButton BtnCor2;
    private javax.swing.JButton BtnPiram;
    private javax.swing.JButton BtnPonto;
    private javax.swing.JButton BtnRet;
    private javax.swing.JButton btnBorracha;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnPoligono;
    private javax.swing.JButton btnReta;
    private javax.swing.JButton btnSpray;
    private java.awt.Canvas canvas1;
    private java.awt.Checkbox cbArea;
    private java.awt.Checkbox cbComprimento;
    private java.awt.Checkbox cbPerimetro;
    private java.awt.Checkbox cbVolume;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpCor1;
    private javax.swing.JPanel jpCor2;
    private javax.swing.JPanel jpPaint;
    // End of variables declaration//GEN-END:variables
}
